story_verse/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books
  resources :chapters
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   get "/login", to: "auth#new", as: "login"
    # Getting the Login Form

    post "/auth", to: "auth#create"
    # Getting the information from the user (via the form)

    delete "/auth", to: "auth#destroy"
    # Loggin Out

end

story_verse/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

story_verse/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :story
  belongs_to :chapter
end

story_verse/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :books
  has_many :stories, through: :books
end

story_verse/app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :books
  has_many :chapters, through: :books
end

story_verse/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stories
  validates_uniqueness_of :name
end

story_verse/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :setup_auth

  def setup_auth
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find(@user_id)
    end
  end

  def authorized
    unless @logged_in
      flash[:message] = "you are not logged in yet!"
      return redirect_to stories_path
    end
  end

end

story_verse/app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:username])

    if @user && @user.authenticate(params[:password])

      flash[:message] = "Logging in #{@user.name}."
      session[:user_id] = @user.id
      redirect_to stories_path
    else
      flash[:message] = "Invalid Username or Password."
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to stories_path
  end

end

story_verse/app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @books = Book.all
  end

  def show
    get_book
  end

  def new
    all_the_vars
    @book = Book.new
  end

  def create
        @book = Book.new(book_params)
        if @book.save

          redirect_to new_chapter_path
        else
          render :new
        end
   end

  def update
      if get_book.update(book_params)
        redirect_to @book
      else
        render :edit
      end
    end

    def destroy
      @book = Book.destroy(params[:id])
      redirect_to books_path
    end

private

  def all_the_vars
    @stories = Story.all
    @story = Story.new
    @chapters = Chapter.all
    @chapter = Chapter.new
  end

  def book_params
    params.require(:book).permit(:story_id, :chapter_id)
  end

  def get_book
    @book = Book.find(params[:id])
  end
end

story_verse/app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authorized
@stories = Story.all
@story = Story.new
    def index
    	@chapters = Chapter.all
    end

    def show
      get_chapter
    end

    def new
      @stories = Story.all
      @story = Story.new
      @chapters = Chapter.all
      @chapter = Chapter.new
      @book = Book.new

    end

    def create
          @chapter = Chapter.create(chapter_params)
          # if @chapter.save
          #   redirect_to "/chapters/new"
          # else
          #   render :new
          redirect_to new_chapter_path
     end

    def update
        if get_chapter.update(chapter_params)
          redirect_to @chapter
        else
          render :edit
        end
      end

      def destroy
        @chapter = Chapter.destroy(params[:id])
        redirect_to chapters_path
      end

  private

      def chapter_params
            params.require(:chapter).permit(:name, :image)
          end

          def get_chapter
            @chapter = Chapter.find(params[:id])
          end
end

story_verse/app/controllers/stories_controller.rb
class StoriesController < ApplicationController
@chapters = Chapter.all
@chapter = Chapter.new
  def index
  	@stories = Story.all
  end

  def show
    get_story
    @chapters = Chapter.all
  end

  def new
    @story  = @current_user.stories.create
  end
  def create
   end

  def update
      if get_story.update(story_params)
        redirect_to @story
      else
        render :edit
      end
    end

    def destroy
      @story = Story.destroy(params[:id])
      redirect_to stories_path
    end

private

    def story_params
          params.require(:story).permit(:name, :description)
        end

        def get_story
          @story = Story.find(params[:id])
        end
end

story_verse/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to stories_path
    else
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

story_verse/app/helpers/application_helper.rb
module ApplicationHelper
end

story_verse/app/helpers/books_helper.rb
module BooksHelper
end

story_verse/app/helpers/chapters_helper.rb
module ChaptersHelper
end

story_verse/app/helpers/stories_helper.rb
module StoriesHelper
end

story_verse/app/helpers/users_helper.rb
module UsersHelper
end

story_verse/app/views/books/new.html.erb
<h1>Choose a Chapter for Story</h1>


<%= form_for @book do |f| %>
  <%= f.label :name %><br>
  <%= f.collection_select :story_id, @stories, :id, :name %><br>
  <%= f.label :name %><br>
  <%= f.collection_select :chapter_id, @chapters, :id, :name %><br>
  <%= f.submit %>
<% end %>

story_verse/app/views/chapters/index.html.erb
<div class="chapterbox">

  <h1> Chapters index page </h1>
  <% @chapters.each do |chapters| %>
  <div class="button"> <%= link_to chapters.name, chapters %> </div>
  <% end %>

</div>

story_verse/app/views/chapters/new.html.erb
<h1> chapters new page </h1>

<% @chapters.each do |chapter| %>
  <h1>Choose a Chapter for Story</h1>
  <%= form_for @book do |f| %>
    <%= f.label :name %><br>
    <%= f.collection_select :story_id, @current_user.stories, :id, :name %><br>
    <%= f.label :name %><br>
    <%= f.collection_select :chapter_id, @chapters, :id , :name %><br>
    <%= f.submit %>
  <% end %>

  <p><%= link_to "Click here to add #{chapter.name} to your story" %></p>
  <img src="<%= chapter.image%>" style=“width:400px;height:500px">
<% end %>

story_verse/app/views/chapters/show.html.erb
<!DOCTYPE html>

<div class="chapter_show_box">
  <h1> Chapter show page </h1>
  <%= @chapter.name %><br>
  <br>
  <img src="<%= @chapter.image%>"><br />
  <br>
  <%= link_to "Add this chapter to your story"  %>
</div>

story_verse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryVerse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <header>

          <% if @logged_in %>

            <ul class='test'>
              <li>
                <%= link_to "All stories", stories_path%>
              </li>
              <li>
                <%= link_to "All chapters", chapters_path %>
              </li>
              <li>
                <%= link_to "Log Out", "/auth", method: :delete %>
              </li>
            </ul>
          <% else %>
            <ul>
            <li>
              <%= link_to "Login", "/login" %>
            </li>
            <li>
              <%= link_to "Register", new_user_path %>
            </li>
            </ul>
          <% end %>

          <% if flash[:message] %>
            <p class="message">
              <%= flash[:message] %>
            </p>
          <% end %>

        </header>
        <%= yield %>
  </body>
</html>

story_verse/app/views/stories/index.html.erb
<div class="welcomebox">
<h1> Welcome to StoryVerse
  <% if @current_user%> 
  <%=  @current_user.name  %> 
  <% end %></h1>
<% if @logged_in %>
<div class="button"><%= link_to "create a new story", new_story_path %></div>
<% end %>
<h2> Here is a list of your stories</h2>

<% if @current_user%>

<% @current_user.stories.each do |story| %>
<ul>
  <span><li> <%= link_to story.name , story %> </li></span>
</ul>
<% end %>
<% else puts "please login or register to see avaliable stories"  %>

<p> please login or register to see avaliable stories</p>
<% end %>
</div>

story_verse/app/views/stories/new.html.erb
<h1>neww  </h1>
<%= form_for @story do |f| %>
<%= f.label :name %>
<%= f.text_field :name  %>
<%= f.submit %>
<% end %>

story_verse/app/views/stories/show.html.erb
<div class="story_show_page">
  <h1><%= @story.name %></h1>
  <%= @story.description %><br>
  <div class="button"><%= link_to "Add more chapters",  new_chapter_path %></div>
  <div class="button"><%= link_to "Delete this story", story_path(@story), method: :delete %></div>
</div>

<div class="grid-container">
  <%  @story.chapters.each do |chapter|%>
    <div class="grid-item">
      <%= chapter.name %><br>
      <br>
      <img src="<%= chapter.image%>" style=“width:400px; height:500px"><br>
      <%= button_to "Delete this chapter", chapter_path, method: :delete %>
    </div>
  <% end %>
</div>

story_verse/app/views/users/new.html.erb
<h1> Registration </h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Register" %>
<% end %>